### ISSUE TITLE
Flying title not rendered

### ISSUE THREAD

**Issue by maxroby** [OpenShot/openshot-qt#110]
Hi, trying to create a new Space Movie Intro title, the Flying text is not rendered, either in the preview nor in the created title.
Thanks.

**Comment by jonoomph** [comment]
I have fixed this bug in the newest release (to be released in the next couple days). There were some issues seeking on these types of animations, and it's much more stable at this now. Thx.

**Comment by nvcleemp** [comment]
I'm still seeing this issue with the latest version OpenShot. I even tried to download the most recent version of the blender file from the repository, but even then no luck. Everything renders fine, except for the title (`TitleSpaceMovie`)
