### ISSUE TITLE
Openshot 2.4.1 Crashed for Ubuntu 16.04

### ISSUE THREAD

**Issue by sunbearc22** [OpenShot/openshot-qt#1678]
I followed your installation [procedure](https://www.openshot.org/ppa/) for Stable PPA (Contains only official releases)
```
sudo add-apt-repository ppa:openshot.developers/ppa
sudo apt-get update
sudo apt-get install openshot-qt 
```
After installation and starting up Openshot, whenever I try to load a image to the project file workspace or click some GUI button, Openshot 2.4.1 crashed. 

Because this version constantly crashed, I had to resort to use OpenShot version 1.4.3, which did not crash.

Is 2.4.1 designed to work on Ubuntu 16.04.4? Any solution for eliminating the crashing?

**Comment by peanutbutterandcrackers** [comment]
OpenShot does work on Ubuntu 16.04. I have used it before. This is indeed quite strange.

I would recommend switching to the daily PPA instead. There have been a lot of improvements since v2.4.1. Also, v2.4.2 will be out soon.

Hope that helps!

[P. S: If even the daily version crashes, please do not forget to [attach the logs](https://github.com/OpenShot/openshot-qt/blob/develop/CONTRIBUTING.md). Thank you!]

**Comment by sunbearc22** [comment]
@peanutbutterandcrackers I have installed Openshot 2.4.1 daily using your instruction:
```
Daily PPA (Highly experimental and unstable, but contains daily updates for testers)
$ sudo add-apt-repository ppa:openshot.developers/libopenshot-daily
$ sudo apt-get update
$ sudo apt-get install openshot-qt
```
I started a terminal and openshot via cmd:
`$ openshot-qt`

Openshot starts up but when I click "Open Project" Button, Openshot immediately shutdowns.

```
~$ openshot-qt
Loaded modules from installed directory: /usr/lib/python3/dist-packages/openshot_qt
      launch:INFO ------------------------------------------------
      launch:INFO    OpenShot (version 2.4.1-dev1)
      launch:INFO ------------------------------------------------
         app:INFO openshot-qt version: 2.4.1-dev1
         app:INFO libopenshot version: 0.1.9
         app:INFO platform: Linux-4.10.0-42-generic-x86_64-with-Ubuntu-16.04-xenial
         app:INFO processor: x86_64
         app:INFO machine: x86_64
         app:INFO python version: 3.5.2
         app:INFO qt5 version: 5.5.1
         app:INFO pyqt5 version: 5.5.1
    language:INFO Attempting to load qt_en_SG.UTF-8 in '/usr/share/qt5/translations'
    language:INFO Attempting to load qt_en in '/usr/share/qt5/translations'
    language:INFO Attempting to load en_SG.UTF-8/LC_MESSAGES/OpenShot in '/usr/lib/python3/dist-packages/openshot_qt/locale'
    language:INFO Attempting to load en/LC_MESSAGES/OpenShot in '/usr/lib/python3/dist-packages/openshot_qt/locale'
    language:INFO Attempting to load qt_en_SG in '/usr/share/qt5/translations'
    language:INFO Attempting to load qt_en in '/usr/share/qt5/translations'
    language:INFO Attempting to load en_SG/LC_MESSAGES/OpenShot in '/usr/lib/python3/dist-packages/openshot_qt/locale'
    language:INFO Attempting to load en/LC_MESSAGES/OpenShot in '/usr/lib/python3/dist-packages/openshot_qt/locale'
    language:INFO Qt Detected Languages: ['en-SG', 'en']
    language:INFO LANG Environment Variable: en_SG.UTF-8
    language:INFO LOCALE Environment Variable: en_SG
    language:INFO Skipping English language (no need for translation): en_SG.UTF-8
    language:INFO Skipping English language (no need for translation): en_SG
project_data:INFO Setting default profile to HDV 720 24p
         app:INFO Setting font to /usr/lib/python3/dist-packages/openshot_qt/images/fonts/Ubuntu-R.ttf
logger_libopenshot:INFO Connecting to libopenshot with debug port: 5556
         app:INFO Setting custom dark theme
connectionpool:INFO Starting new HTTP connection (1): www.google-analytics.com
connectionpool:INFO Starting new HTTP connection (1): www.google-analytics.com
link SVGID_18_-5 hasn't been detected!
link SVGID_18_-5 hasn't been detected!
link SVGID_22_-5 hasn't been detected!
link SVGID_24_-2 hasn't been detected!
link SVGID_24_-2 hasn't been detected!
     metrics:INFO Track metric: [200] http://www.google-analytics.com/collect?av=2.4.1-dev1&cd4=5.5.1&ua=Mozilla%2F5.0+%28X11%3B+Linux+x86_64%29+AppleWebKit%2F537.36+%28KHTML%2C+like+Gecko%29+Chrome%2F37.0.2062.120+Safari%2F537.36&v=1&sc=start&cd1=0.1.9&aip=1&cd=launch-app&cid=23dc74b6-938b-4971-99a6-e202a622c15c&tid=UA-4381101-5&cd5=Ubuntu-16.04-xenial&ul=en&aid=org.openshot.openshot-qt&cd2=3.5.2&t=screenview&an=OpenShot+Video+Editor&cd3=5.5.1 | (35 bytes)
     metrics:INFO Track metric: [200] http://www.google-analytics.com/collect?av=2.4.1-dev1&cd4=5.5.1&ua=Mozilla%2F5.0+%28X11%3B+Linux+x86_64%29+AppleWebKit%2F537.36+%28KHTML%2C+like+Gecko%29+Chrome%2F37.0.2062.120+Safari%2F537.36&v=1&cd1=0.1.9&aip=1&cd=main-screen&cid=23dc74b6-938b-4971-99a6-e202a622c15c&tid=UA-4381101-5&cd5=Ubuntu-16.04-xenial&ul=en&aid=org.openshot.openshot-qt&cd2=3.5.2&t=screenview&an=OpenShot+Video+Editor&cd3=5.5.1 | (35 bytes)
     ui_util:INFO Initializing UI for MainWindow
     ui_util:INFO Binding event MainWindow:actionNew_trigger
     ui_util:INFO Binding event MainWindow:actionOpen_trigger
     ui_util:INFO Binding event MainWindow:actionSave_trigger
     ui_util:INFO Binding event MainWindow:actionUndo_trigger
     ui_util:INFO Binding event MainWindow:actionSaveAs_trigger
     ui_util:INFO Binding event MainWindow:actionImportFiles_trigger
     ui_util:INFO Binding event MainWindow:actionImportImageSequence_trigger
     ui_util:INFO Binding event MainWindow:actionRedo_trigger
     ui_util:INFO Binding event MainWindow:actionRemoveClip_trigger
     ui_util:INFO Binding event MainWindow:actionRemoveTransition_trigger
     ui_util:INFO Binding event MainWindow:actionExportVideo_trigger
     ui_util:INFO Binding event MainWindow:actionUploadVideo_trigger
     ui_util:INFO Binding event MainWindow:actionAddTrack_trigger
     ui_util:INFO Binding event MainWindow:actionPreferences_trigger
     ui_util:INFO Binding event MainWindow:actionPlay_trigger
     ui_util:INFO Binding event MainWindow:actionJumpStart_trigger
     ui_util:INFO Binding event MainWindow:actionRewind_trigger
     ui_util:INFO Binding event MainWindow:actionFastForward_trigger
     ui_util:INFO Binding event MainWindow:actionJumpEnd_trigger
     ui_util:INFO Binding event MainWindow:actionArrowTool_trigger
     ui_util:INFO Binding event MainWindow:actionRazorTool_trigger
     ui_util:INFO Binding event MainWindow:actionSnappingTool_trigger
     ui_util:INFO Binding event MainWindow:actionAddMarker_trigger
     ui_util:INFO Binding event MainWindow:actionPreviousMarker_trigger
     ui_util:INFO Binding event MainWindow:actionNextMarker_trigger
     ui_util:INFO Binding event MainWindow:actionFilesShowAll_trigger
     ui_util:INFO Binding event MainWindow:actionFilesShowVideo_trigger
     ui_util:INFO Binding event MainWindow:actionFilesShowAudio_trigger
     ui_util:INFO Binding event MainWindow:actionFilesShowImage_trigger
     ui_util:INFO Binding event MainWindow:actionTransitionsShowAll_trigger
     ui_util:INFO Binding event MainWindow:actionTransitionsShowCommon_trigger
     ui_util:INFO Binding event MainWindow:actionEffectsShowAll_trigger
     ui_util:INFO Binding event MainWindow:actionEffectsShowVideo_trigger
     ui_util:INFO Binding event MainWindow:actionEffectsShowAudio_trigger
     ui_util:INFO Binding event MainWindow:actionTimelineZoomIn_trigger
     ui_util:INFO Binding event MainWindow:actionTimelineZoomOut_trigger
     ui_util:INFO Binding event MainWindow:actionTitle_trigger
     ui_util:INFO Binding event MainWindow:actionAnimatedTitle_trigger
     ui_util:INFO Binding event MainWindow:actionFullscreen_trigger
     ui_util:INFO Binding event MainWindow:actionAbout_trigger
     ui_util:INFO Binding event MainWindow:actionThumbnailView_trigger
     ui_util:INFO Binding event MainWindow:actionDetailsView_trigger
     ui_util:INFO Binding event MainWindow:actionReportBug_trigger
     ui_util:INFO Binding event MainWindow:actionAskQuestion_trigger
     ui_util:WARNING Icon theme im-message-new not found. Will use backup icon.
     ui_util:INFO Binding event MainWindow:actionTranslate_trigger
     ui_util:INFO Binding event MainWindow:actionDonate_trigger
     ui_util:INFO Binding event MainWindow:actionHelpContents_trigger
     ui_util:INFO Binding event MainWindow:actionSimple_View_trigger
     ui_util:INFO Binding event MainWindow:actionAdvanced_View_trigger
     ui_util:INFO Binding event MainWindow:actionFreeze_View_trigger
     ui_util:INFO Binding event MainWindow:actionUn_Freeze_View_trigger
     ui_util:INFO Binding event MainWindow:actionShow_All_trigger
     ui_util:INFO Binding event MainWindow:actionProfile_trigger
     ui_util:INFO Binding event MainWindow:actionAdd_to_Timeline_trigger
     ui_util:INFO Binding event MainWindow:actionPreview_File_trigger
     ui_util:INFO Binding event MainWindow:actionRemove_from_Project_trigger
     ui_util:INFO Binding event MainWindow:actionFile_Properties_trigger
     ui_util:INFO Binding event MainWindow:actionRemoveTrack_trigger
     ui_util:INFO Binding event MainWindow:actionRemoveMarker_trigger
     ui_util:INFO Binding event MainWindow:actionAddTrackAbove_trigger
     ui_util:INFO Binding event MainWindow:actionAddTrackBelow_trigger
     ui_util:INFO Binding event MainWindow:actionRemoveEffect_trigger
     ui_util:INFO Binding event MainWindow:actionSplitClip_trigger
     ui_util:INFO Binding event MainWindow:actionProperties_trigger
     ui_util:INFO Binding event MainWindow:actionRenameTrack_trigger
     ui_util:INFO Binding event MainWindow:actionUpdate_trigger
     ui_util:INFO Binding event MainWindow:actionTutorial_trigger
     ui_util:WARNING Icon theme im-message-new not found. Will use backup icon.
     ui_util:INFO Binding event MainWindow:actionAnimation_trigger
     ui_util:INFO Binding event MainWindow:actionLockTrack_trigger
     ui_util:INFO Binding event MainWindow:actionUnlockTrack_trigger
     ui_util:WARNING Icon theme transform-move not found. Will use backup icon.
     ui_util:INFO Binding event MainWindow:actionEditTitle_trigger
     ui_util:INFO Binding event MainWindow:actionDuplicateTitle_trigger
     ui_util:INFO Binding event MainWindow:actionClearHistory_trigger
connectionpool:INFO Starting new HTTP connection (1): www.openshot.org
 files_model:INFO updating files model.
transition_model:INFO updating transitions model.
effects_model:INFO updating effects model.
effects_model:INFO category: Video
effects_model:INFO category: Video
effects_model:INFO category: Video
effects_model:INFO category: Video
effects_model:INFO category: Video
effects_model:INFO category: Video
effects_model:INFO category: Video
effects_model:INFO category: Video
effects_model:INFO category: Video
effects_model:INFO category: Video
effects_model:INFO category: Video
effects_model:INFO category: Video
effects_model:INFO category: Video
effects_model:INFO category: Video
properties_model:INFO updating clip properties model.
 main_window:INFO InitCacheSettings
 main_window:INFO cache-mode: CacheMemory
 main_window:INFO cache-limit-mb: 250
 main_window:INFO Creating CacheMemory object with 262144000 byte limit
preview_thread:INFO QThread Start Method Invoked
preview_thread:INFO initPlayer
 main_window:ERROR Unhandled crash detected... will attempt to recover backup project: /home/sunbear/.openshot_qt/backup
connectionpool:INFO Starting new HTTP connection (1): www.google-analytics.com
    tutorial:INFO process tutorial dialogs
 main_window:INFO updateStatusChanged
         app:INFO Process command-line arguments: ['/usr/bin/openshot-qt']
 main_window:INFO recover_backup
project_data:INFO Setting default profile to HDV 720 24p
preview_thread:INFO refreshFrame
preview_thread:INFO self.player.Position(): 1
timeline_webview:ERROR TimelineWebView::eval_js() called before document ready event. Script queued: $('body').scope().SetTrackLabel('Track %s');
timeline_webview:ERROR TimelineWebView::eval_js() called before document ready event. Script queued: $('body').scope().LoadJson({"value": {"height": 720, "channel_layout": 3, "profile": "HDV 720 24p", "export_path": "", "fps": {"num": 24, "den": 1}, "sample_rate": 44100, "progress": [], "files": [], "layers": [{"number": 0, "y": 0, "label": "", "id": "L0", "lock": false}, {"number": 1, "y": 0, "label": "", "id": "L1", "lock": false}, {"number": 2, "y": 0, "label": "", "id": "L2", "lock": false}, {"number": 3, "y": 0, "label": "", "id": "L3", "lock": false}, {"number": 4, "y": 0, "label": "", "id": "L4", "lock": false}], "version": {"libopenshot": "0.0.0", "openshot-qt": "0.0.0"}, "width": 1280, "clips": [], "channels": 2, "effects": [], "id": "T0", "history": {"redo": [], "undo": []}, "scale": 16, "settings": {}, "tick_pixels": 100, "import_path": "", "playhead_position": 0, "markers": [], "duration": 300}, "key": "", "partial": false, "type": "load", "old_values": null});
 main_window:INFO updateStatusChanged
     metrics:INFO Track metric: [200] http://www.google-analytics.com/collect?av=2.4.1-dev1&cd4=5.5.1&ua=Mozilla%2F5.0+%28X11%3B+Linux+x86_64%29+AppleWebKit%2F537.36+%28KHTML%2C+like+Gecko%29+Chrome%2F37.0.2062.120+Safari%2F537.36&v=1&exd=unhandled-crash&cd1=0.1.9&aip=1&cid=23dc74b6-938b-4971-99a6-e202a622c15c&tid=UA-4381101-5&cd5=Ubuntu-16.04-xenial&exf=1&ul=en&aid=org.openshot.openshot-qt&cd2=3.5.2&t=exception&an=OpenShot+Video+Editor&cd3=5.5.1 | (35 bytes)
timeline_webview:ERROR TimelineWebView::eval_js() called before document ready event. Script queued: $('body').scope().SetSnappingMode(1);
timeline_webview:INFO Qt Found!
timeline_webview:INFO $scope.Qt = true;
preview_thread:INFO onModeChanged
timeline_webview:INFO UpdateLayerIndex
timeline_webview:INFO UpdateLayerIndex
properties_model:INFO Update item: 
properties_model:INFO updating clip properties model.
preview_thread:INFO refreshFrame
preview_thread:INFO self.player.Position(): 1
    timeline:INFO Adjusting max size of preview image: PyQt5.QtCore.QRect(57, 0, 700, 394)
     version:INFO Found current version: {"openshot_version": "2.4.1"}
 main_window:INFO foundCurrentVersion: Found the latest version: 2.4.1
Caught signal 11 (SIGSEGV)
---- Unhandled Exception: Stack Trace ----
---- End of Stack Trace ----
```
Also when I try to load image files to Project Area, it crashes(i.e.shutdowns) immediately with the following error:
```
Caught signal 11 (SIGSEGV)
---- Unhandled Exception: Stack Trace ----
---- End of Stack Trace ----
```
What can I do next to help get the latest Openshot version work on my Ubuntu 16.04.4 system?

**Comment by peanutbutterandcrackers** [comment]
Good sir, thank you for your willingness to help.

First, please go to your `.openshot_qt` folder in your home directory (it's hidden by default, you might have to get your file manager to show hidden files). Once you're there, delete all files ending with `.log`. After that, please go ahead and open OpenShot and reproduce the crash. As soon as the program crashes, head over back to `.openshot_qt`. From there, please get the files ending with `.log` and attach it in your next comment (perhaps zip it before upload?). I will try to get the devs attention towards this.

:)

**Comment by sunbearc22** [comment]
The Files you had requested are attached:
[libopenshot.log](https://github.com/OpenShot/openshot-qt/files/2092510/libopenshot.log)
[openshot-qt.log](https://github.com/OpenShot/openshot-qt/files/2092511/openshot-qt.log)

**Comment by peanutbutterandcrackers** [comment]
Awesome! Thank you! I will let the devs know about this issue, soon! Thank you!

Sorry for the inconvenience, and thank you for your patience! :)

**Comment by sunbearc22** [comment]
@peanutbutterandcrackers There was an Openshot-qt update via ppa today. After the update, the same crashing issues still persists. The new .log files are attached for your follow-up. 

[openshot-qt.log](https://github.com/OpenShot/openshot-qt/files/2096297/openshot-qt.log)
[libopenshot.log](https://github.com/OpenShot/openshot-qt/files/2096298/libopenshot.log)

**Comment by sunbearc22** [comment]
@peanutbutterandcrackers did devs manage to figure out or reproduce the issue?

**Comment by peanutbutterandcrackers** [comment]
I am sorry I haven't been able to get back to this sooner...

No, I am sorry I haven't really been able to get their attention to this. However, taking a look at the logs myself, it seems we need to turn verbose mode on (there aren't any clear indicators as to why it is crashing). Could you please go to `Edit` > `Preferences` > `Debug` and turn on `Debug mode (verbose)` by checking it? But before that, please delete your `.openshot_qt` directory all together. And once you've turned on the verbose debug mode, restart OpenShot and reproduce the crash ASAP and then attach the logs here.

Strange, I think my brother is using OpenShot latest daily build on his Ubuntu 16.04 machine back at home. I don't see any reason why OpenShot should crash on Ubuntu 16.04. Esp. because as far as I can remember, our lead developer and BDFL Mr. Thomas uses an Ubuntu Machine for primary development.

@DylanC - Any ideas, good sir?

**Comment by DylanC** [comment]
@peanutbutterandcrackers - The OpenShot version still says v2.4.1. @sunbearc22 - Can you try the daily build for us first? Should be much better and reliable. Do let us know if you still have the same problem with it.

**Comment by peanutbutterandcrackers** [comment]
@DylanC - v2.4.1 worked for me on my Ubuntu 16.04 machine, though. But all right.

@sunbearc22 - [Here](https://gist.github.com/peanutbutterandcrackers/3618493b99ba08003e4e4b1602459914) is how you get a hold of the daily builds. All the very best!

**Comment by sunbearc22** [comment]
@peanutbutterandcrackers I am not able to change the preference. Whenever I click on "Preference", Openshot-qt crashes immediately.

@DylanC and @peanutbutterandcrackers I am using Openshot-qt's daily build. This is what I get on the terminal.
```
$ openshot-qt --version
Loaded modules from installed directory: /usr/lib/python3/dist-packages/openshot_qt
      logger:INFO OpenShot version 2.4.1-dev1
```

The following are the Openshot packages installed on my system:
```
$ dpkg -l | grep openshot
ii  libopenshot-audio6:amd64    0.1.5+dfsg2+61+201806122158~ubuntu16.04.1        amd64   library for high-quality audio editing
ii  libopenshot14:amd64         0.1.9+dfsg2+678+201806122219+daily~ubuntu16.04.1 amd64   library for high quality video editing
ii  openshot                    1.4.3-1.2                                        all     Create and edit videos and movies
ii  openshot-doc                1.4.3-1.2                                        all     Help manual for OpenShot Video Editor
ii  openshot-qt                 2.4.1+dfsg2+932+201806171802~ubuntu16.04.1       all     OpenShot video editor
ii  openshot-qt-doc             2.4.1+dfsg2+932+201806171802~ubuntu16.04.1       all     documentation for OpenShot
ii  python3-openshot:amd64      0.1.9+dfsg2+678+201806122219+daily~ubuntu16.04.1 amd64   Python bindings for the OpenShot library
```
My Ubuntu kernel version:
```
$ uname -v
#46~16.04.1-Ubuntu SMP Mon Dec 4 15:57:59 UTC 2017
```

**Comment by sunbearc22** [comment]
@peanutbutterandcrackers I looked through the past "openshot-qt.log" files I had uploaded above and they all state `OpenShot (version 2.4.1-dev1) `. I had thought the `-dev1` had referred to daily build. 

Also, the daily build instruction link shows the same procedure that I had used, which I had wrote in my comments ([see above](https://github.com/OpenShot/openshot-qt/issues/1678#issuecomment-396457174)) 8 days ago.

**Comment by peanutbutterandcrackers** [comment]
@sunbearc22 - Hmm... I will post this thread to the devs slack channel to get their attention. Sorry for keeping you waiting. Could you please perform an upgrade in the meantime? Thanks!

Done! Reported!

**Comment by DylanC** [comment]
@sunbearc22 Can you try v2.4.2 and let us know if you have any success?

**Comment by sunbearc22** [comment]
@DylanC I have the following version installed, but I am still facing the same issue.

```
$ dpkg -l | grep openshot-qt
ii  openshot-qt                                 2.4.2+dfsg2+954+201807202147~ubuntu16.04.1       all          OpenShot video editor
ii  openshot-qt-doc                             2.4.2+dfsg2+954+201807202147~ubuntu16.04.1       all          documentation for OpenShot
```

**Comment by ferdnyc** [comment]
I hadn't seen this before, and I realize it's months old so I don't know if @sunbearc22 is still having the same issue, but if it's still waiting on being reproduced then I suspect it's waiting in vain. 

1. _Many_ users regularly run OpenShot 2.4.x on Ubuntu 16.04.4, from that same PPA, with no issues; the issue is clearly something unusual and specific to @sunbearc22 's environment. 
1. OpenShot seems to be dying right when it _finishes_ its startup, basically — at exactly the point where it would normally start logging messages from user actions, if any. The crash occurs right when **nothing** is expected to be happening.

Those two things together mean that the odds of anyone being able to reproduce this are incredibly slim, I'm afraid. Not without some way of knowing what's causing it. (Beyond "just run `openshot-qt`", since normally that **doesn't** cause a crash.) I completely understand that you've provided all the info you have available, @sunbearc22 , it's just that unfortunately it's still very little to go on.

Some thoughts, though:
1. Unless I missed it, I don't think at ant point that trying an [AppImage](https://www.openshot.org/download/) was ever suggested. The issue is long past the point where it makes sense to abandon the PPA builds entirely and try something different. An AppImage build would be that something. (Just not the 2.4.2 release AppImage, since we know that suffers from #1757 on some systems, including Ubuntu IIRC.)
   One of* the [2.4.3-release-candidate](https://github.com/OpenShot/openshot-qt/releases/download/daily/OpenShot-v2.4.3-release-candidate-1537226416-x86_64.AppImage)s would seem like a reasonable option, now that that's a thing.
1. In the same "radical debugging" vein, I'd recommend deleting-or-renaming `$HOME/.openshot_qt` _entirely_ (not just the log files), then try to launch `openshot-qt`. Perhaps something there is screwing things up. This is especially worth trying if the AppImage also crashes (since it will use your settings and data files from `$HOME/.openshot_qt` if present.)
1. Am I reading correctly, that OpenShot 1.4.3 is **also** _still_ installed on your machine, @sunbearc22 ? If so, I... can imagine that _might_ be causing problems; I don't know for sure that it does, but that's mostly because I don't know anyone who's ever tried that. OpenShot 2.x coexisting alongside 1.4.x is probably an "undefined behavior" situation at best.
   It's probably worth uninstalling `openshot` and `openshot-doc` 1.4.3 (AKA the very, very old version), in case that's what's messing up 2.4.x.
   1. However, if you wanted to wait before taking that step, the AppImages should be pretty well isolated from the rest of the system, so you could try that _first_. If OpenShot 2.4.x does indeed run from the AppImage, then uninstalling 1.4.3 might get the PPA build working as well.

\* — (It looks like "2.4.3-release-candidate" = every new autobuild off the release branch, oddly.)

**Comment by peanutbutterandcrackers** [comment]
@ferdnyc - Always fascinated with your deductions, good sir. Cyber-Sherlock, like always. :+1:

**Comment by sunbearc22** [comment]
@ferdnyc Thank you for you comment. 

I have tried Openshot AppImage 2.4.3 version. That works well, except that the `Animation Title` had issue because it needed Blender 2.78 ver while I only had Blender v2.76.

Concerning version 2.4.2-dev1, an interesting development is that it is able to work to a certain extent. That is, the Window opens, I am able to load an video files, put them on tracks, cut the video clips and add transitions and effects. **BUT** when I do click on any of the items on the menu, e.g. to `Save` my file, or to `Open` a new file, the software will immediately shut down w/o warnings.

**Comment by ferdnyc** [comment]
> Btw, while tinkering, I had to install `pypar2`. Will update if that had helped my situation. 

Hmm. 

[Package: pypar2 — graphical frontend for the par2 utility (PAR 2.0 compatible file verification and repair tool)](https://packages.ubuntu.com/xenial/pypar2)

There's no reason that should have anything to do with OpenShot, it certainly isn't used by any part of the OpenShot code. I don't know why you'd have had to install it, but I assume it was required by some Ubuntu tool.

> But I noticed the following:
> 
> ```
> $ sudo apt purge pypar2
> Reading package lists... Done
> Building dependency tree       
> Reading state information... Done
> The following packages were automatically installed and are no longer required:
>   libgoocanvas-common libgoocanvas3 libmlt++3 libmlt-data libmlt6 libmovit4 libopenshot-audio6 libopenshot16 libqt5multimediawidgets5 libsox-fmt-alsa libsox-fmt-base libsox2
>   libvte-common libvte9 melt openshot-doc par2 python-httplib2 python-mlt python-pygoocanvas python-vte python3-openshot python3-pyqt5.qtmultimedia python3-pyqt5.qtopengl
>   python3-pyqt5.qtsvg python3-pyqt5.qtwebkit python3-zmq
> Use 'sudo apt autoremove' to remove them.
> ```

I assume that was while you _didn't_ have `openshot-qt` installed, right? In which case, it makes sense that `libopenshot16` and `python3-openshot` and etc. would not be required at that point. Did you do the suggested `sudo apt autoremove`, before you reinstalled `openshot-qt`?

If you didn't, then the way I'm reading this, it looks like you really only removed/reinstalled the `openshot-qt` component, which is just the user interface for OpenShot. That's just one of several packages in the PPA.

I normally wouldn't put someone through all of this, especially not _again_... but since you're still having problems that are, frankly, inexplicable (and since the 2.4.3 AppImage works for you, so we know that OpenShot _can_ be run on your system), I'd recommend _completely_ cleaning out OpenShot and all of its component parts, then reinstalling. So:

```sh
sudo apt purge openshot-qt # Uninstall the OpenShot application

sudo apt autoremove # Remove dependencies, since apparently "purge" doesn't quite mean "purge"
```

That should remove at least libopenshot16, libopenshot-audio6, python3-libopenshot, etc., which are the "rest" of OpenShot 2.4.3. It'll also remove things like `python-mlt`, which is left over from OpenShot 1.x and no longer used at all in OpenShot 2. 

And it looks like it'll probably further remove part/all of python3-pyqt5, python3-zmq, etc. (Dependencies that aren't used by anything except OpenShot, on your system.) The more the merrier, as now the necessary parts (and only the necessary parts) can be pulled back in automatically as dependencies:

```sh
# Reinstall OpenShot from the PPA, along with its libraries and any required dependencies
sudo apt install openshot-qt
```

I guess, see what happens then? `¯\_(ツ)_/¯`

(Disclaimer: I'm a Fedora user, so I'm also making all of these commands up based on context/assumptions, having never actually used `apt` myself. If anything I suggest sounds stupid/dangerous/wrong, I'd recommend you assume that's because _it is_, and don't do it.)
