### ISSUE TITLE
No Audio in Preview

### ISSUE THREAD

**Issue by SunnyTurtle** [OpenShot/openshot-qt#1975]
I get no audio when preview a video or when I play through the video preview. Is there meant to be sound?

I use sound ques when editing. So I really can't use OpenShot with this issue

Same Issue as
https://github.com/OpenShot/openshot-qt/issues/721

 - Operating System Windows 10
 - OpenShot Version 2.4.2

**Comment by speedytechdev** [comment]
Hi, @SunnyTurtle  I would recommend you use 2.4.3 since this fixed a lot of bugs and if you are still having issues after that let me know.

**Comment by SunnyTurtle** [comment]
Hi @speedytechdev , No luck unfortunately still having exact same issue with a fresh install of 2.4.3. I am no longer using open shot but would be happy to test it for you as it seems like a few people have this issue.

**Comment by speedytechdev** [comment]
I am sorry to hear that. If you are still willing to help could you get as much information as possible on the issue so it makes it easy for the devs to fix it.

**Comment by peanutbutterandcrackers** [comment]
@mirkojovic - Hey, that just might be the case. Perhaps you could try importing the same video trans-coded in a different format (perhaps .mkv) using [HandBrake](https://handbrake.fr/) and see if that resolves the issue?

@SunnyTurtle - Thank you for your willingness to help. Could you also please try the same thing that I have suggested to @mirkojovic ? Thanks!

**Comment by StephenTurley** [comment]
I'm having the same issue in 2.4.4 on PopOS. Imported a mkv that I created with https://www.maartenbaert.be/simplescreenrecorder/.

Was able to to export the video and the audio is great in the export, but I'm unable to hear anything in preview mode. Let me know if you need anything to help troubleshoot.

**Comment by ferdnyc** [comment]
@StephenTurley 

I would suggest downloading the latest Daily Build AppImage from the [download page](https://www.openshot.org/download/) (click "Daily Builds" below the download link), and give that a try. Since 2.4.4 was released, we've added an audio output device selector to the preferences, along with better checks of the audio output setup. It's possible OpenShot is using the wrong output device.

**Comment by StephenTurley** [comment]
Thanks, I downloaded the latest build and was given several options for my preferred output device (Modi 2; USB). I tried several of the options. Each time I restarted I was given the following error:

> Please fix the following error and restart OpenShot
> no channels

Along with no audio output in preview.

**Comment by StephenTurley** [comment]
Ahh I figured it out. I had to set the channels after setting the device. Seems like the current channel configuration isn't applied to the new device selected. Works great! Thank you.

**Comment by ferdnyc** [comment]
Glad to hear you solved it!

> I had to set the channels after setting the device. Seems like the current channel configuration isn't applied to the new device selected.

I'm curious about that channel setting: Is that the channel layout in OpenShot, or an OS configuration? (I'm just wondering if there's more we can do to prevent those issues in the future.)

**Comment by StephenTurley** [comment]
Yes its the channel layout setting in OpenShot. I had to set it to mono then back to stereo to get it to work. Seems like when the device is chosen, it doesn't keep the current channel configuration.

**Comment by ferdnyc** [comment]
Hmm, interesting. It's _supposed_ to, unless it's picking up a different/incompatible configuration from the audio device itself.

PopOS uses Pulseaudio? And you're outputting to, what... a local audio device? (Not Bluetooth or anything like that.)

If you'd be willing, a copy of some configs from your system would be extremely helpful.

1. `pacmd dump > /tmp/pacmd.txt`
1. `alsa-info.sh --with-devices --with-configs --with-aplay --no-upload --output /tmp/alsa-info.txt`
1. Your `$HOME/.openshot_qt/openshot.settings`, now that it's working.

GitHub will accept either the individual `.txt` files as comment attachments (the `openshot.settings`, too, if you rename it to `openshot.settings.txt`), or a `.zip` file of all three together.

**Comment by StephenTurley** [comment]
I'm using a DAC connected via USB. This here: https://hometheaterhifi.com/blogs/schiit-modi-2-desktop-dac-review/

I think PopOS uses pulseaudio but I'm not sure. Its probably the same that Ubuntu ships with. 
[alsa-info.txt](https://github.com/OpenShot/openshot-qt/files/3490562/alsa-info.txt)
[openshot.settings.txt](https://github.com/OpenShot/openshot-qt/files/3490563/openshot.settings.txt)
[pacmd.txt](https://github.com/OpenShot/openshot-qt/files/3490564/pacmd.txt)

**Comment by ferdnyc** [comment]
> I'm using a DAC connected via USB.

Aha! Gotcha. That _shouldn't_ be too esoteric.

> I think PopOS uses pulseaudio but I'm not sure.

Sure does, as demonstrated by it having a `pacmd`.

Much appreciated on the logs. Unfortunately, there's nothing really unusual there, that would seem to explain this. I'm _guessing_, at this point, that the "culprit" is here:
<pre>
    {
        "title": "Playback Audio Device",
        "category": "Preview",
        "values": [],
        "restart": true,
        "type": "dropdown",
        "value": "Modi 2, USB Audio; <b>Direct hardware device without any conversions</b>",
                                     <b>^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^</b>
        "setting": "playback-audio-device"
    },
</pre>

\*shrug\* Maybe that interfered with the channel-layout detection somehow. Anyway, thanks again.

**Comment by ferdnyc** [comment]
I'm going to close this, since the original report is very old, and I believe would've also been aided/solved by the audio-device selector and other changes made since the original report.

(The only one I can't explain is the issue @mirkojovic was having, since it was codec-dependent, not device-dependent. But if anyone is seeing that in 2.4.4 or Daily Builds, still, please open a new issue with current details.

**Comment by bergmeister** [comment]
@ferdnyc Using `OpenShot` version `2.5.1`, this is still an issue. Let me explain the scenario:

My default audio output when nothing is plugged in, are the laptop speakers (which do not work for me). Therefore I am plugging in a Realtek USB headset and once it is plugged in, the OS (Windows 10 1909) uses this as the default sound output and any app respects that except for OpenShot. I had to go into `Preferences` -> `Preview` ->`Playback Audio Device` and select that device and had to restart OpenShot (which is something that shouldn't really be needed but I can live with that). The origin of the problem here is that the meaning of the `Default` playback audio device should rather be the currently used default audio device (at least on startup of OpenShot due to the restart issue), which is not the case at the moment.

**Comment by ferdnyc** [comment]
@bergmeister 

> My default audio output when nothing is plugged in, are the laptop speakers (which do not work for me). Therefore I am plugging in a Realtek USB headset and once it is plugged in, the OS (Windows 10 1909) uses this as the default sound output and any app respects that except for OpenShot. I had to go into `Preferences` -> `Preview` ->`Playback Audio Device` and select that device and had to restart OpenShot (which is something that shouldn't really be needed but I can live with that). The origin of the problem here is that the meaning of the `Default` playback audio device should rather be the currently used default audio device (at least on startup of OpenShot due to the restart issue), which is not the case at the moment.

We use the JUCE library's `AudioDeviceManager` to build the list we display of the the available audio outputs on the system. If one is selected in the Preferences we pass that in as the preferred device name when we open the audio output. If the selection is "Default" that simply means passing an empty string in as the selection, which should use the default -- but probably the _hardware_ default, not necessarily Windows' selection, I suppose.

I'll see if there's any API we can use to pull in the Windows audio device configs. It's a bit tricky for me to test, because the only Windows environment I have to test in is a Win7 install running in a VM, so it has no actual audio hardware at all.

**Comment by Claakin** [comment]
This is still, to this day giving me trouble, I have no playback, no matter the device, no matter the setting, no matter the channel... matter of fact, if I choose 2 channel(Stereo) the mfer crashes when I click play to preview.

**Comment by gigajosh** [comment]
I'd just like to mention that I had this problem only when opening the project file via the Recent Projects menu option.
When I open a project file by using Open and selecting the .opd file the problem went away. I'm on a Mac with v2.5.1

**Comment by Tamarindo94** [comment]
The problem still exists on version 2.6.1

**Comment by speedytechdev** [comment]
@ferdnyc ^^^

**Comment by bernard01** [comment]
I have downloaded the software for the first time, fresh 2.6.1 version so all settings are default. OS is Windows 7. I can play MP3 and MP4 video files with VLC media player where the default output goes to my earplugs or speakers consistent with system settings. I cannot make a video without audio. Which is critical. I see this issue is closed. This is really wonderful software. Something must be missing. How do other people do it?
