### ISSUE TITLE
Openshot not opening OPS Files gives error.......

### ISSUE THREAD

**Issue by Cinnamon2013** [OpenShot/openshot-qt#2429]
**Please fill out this template** 

Python script failure when opening OPS files
I get an error when opening OPS files (another user asked this a few months ago here: https://github.com/OpenShot/openshot-qt/issues/1854 but they got no help)

**System Details (please complete the following information):**
 - Windows 10 latest version (what other option is there with windows 10 :P
 - OpenShot Version 2.4.3

**To Reproduce**
1. Try to open an OPS file with openshot
2. See erorr

**Expected behavior**
Open the OPS File

**Screenshots**
![image](https://user-images.githubusercontent.com/19432304/49486496-a6691280-f80c-11e8-89ae-77aea4865864.png)

**Logs**
Not sure if there would be any logs for this

**Comment by Cinnamon2013** [comment]
> 
> 
> From another user "A similar issue had arisen with 2.4.1 too. And it was worked-around by deleting the .openshot_qt folder and re-opening the program. Perhaps it'll help you, too?"
> 
> Did you open the osp file in Openshot or in the file explorer

I opened it with Openshot, not with file explorer, and I don't know how to find the .openshot_qt folder

**Comment by speedytechdev** [comment]
@peanutbutterandcrackers Can you help with this, please.

**Comment by peanutbutterandcrackers** [comment]
Ah! Ah! I see. I think this is an issue that somehow sneaked in to the main release but has been resolved so with future release this issue won't be arising. For now, however, you'll have to open OpenShot first and then open the `.osp` file from `File` > `Open` and that'll do the trick.

For OpenShot itself not starting, please go to your `My Documents` folder, and go to it's parent folder (the one that contains 'My Documents'). There you should see another folder named `.openshot_qt`. Delete that and it should work.

Hope that helps.

**Comment by Cinnamon2013** [comment]
> 
> 
> Ah! Ah! I see. I think this is an issue that somehow sneaked in to the main release but has been resolved so with future release this issue won't be arising. For now, however, you'll have to open OpenShot first and then open the `.osp` file from `File` > `Open` and that'll do the trick.
> 
> For OpenShot itself not starting, please go to your `My Documents` folder, and go to it's parent folder (the one that contains 'My Documents'). There you should see another folder named `.openshot_qt`. Delete that and it should work.
> 
> Hope that helps.

Thank you so much!

**Comment by drdan811** [comment]
I have the same original issue as mentioned at the start of the topic. I have done all suggested here, but still cannot open my .osp file. I keep getting this error "Failed to load project file C:/Users/Dan/Documents/showreel master.osp: invalid load key, '{'."
I have the latest daily (OpenShot-v2.4.3-dev2-1546131314-a8f75a5b-3861a2c5-x86_64.exe (64-bit)), I have tried other dailys and also the main download file, I am on windows 8.1. Please help, I just need to make a couple of small changes to my project and I will be finished!!
Thanks,
Dan

**Comment by peanutbutterandcrackers** [comment]
@drdan811 - Could you please zip the `.osp` file and attach it here for us to see?

**Comment by peanutbutterandcrackers** [comment]
@drdan811 - I see. Then that means it is an issue with the latest dev version on windows (windows, *smh*), as mentioned in #2500. Please follow the discussion over there. For the time being, according to the thread there, you could use an earlier dev version and it'll work fine. Perhaps that is what you should do for now. However, I would suggest that you stick around in the other issue so that the devs can get further information from you as needed - log files, system specs, updates, etc. That way we can get it all fixed for the next stable release. Hope that helps!

**Comment by despacitoing** [comment]
Hi, sorry I'm new to the forum and am not sure if I am allowed to do this, but I really need help.

**Comment by ferdnyc** [comment]
Closing as dup of #2500.
