### ISSUE TITLE
OpenShot won't zoom in enough on timeline

### ISSUE THREAD

**Issue by not83** [OpenShot/openshot-qt#286]
The most you can zoom in timeline is 8 seconds. How on earth am I meant to line clips up to the millimetre where I want it if I have to be stuck with 8 seconds on my timeline. I need to be able to zoom in a lot more.

Ubuntu 14.04 
8 gig ram
version : OpenShot version 2.0.7
i5-4570
660ti nvidia

**Comment by tester2011** [comment]
Yes, this is a deal-breaker for me - the zoom function needs to be much more flexible.

The current limit of 8 seconds makes detailed editing and positioning of transitions almost impossible.

Ideally it should allow a 'minimum' zoom of 1 second (or less!).

Cheers,

Mike.

(Running OpenShot 2.1.0 on Linux Mint 18.0 64-bit xfce )

**Comment by jonoomph** [comment]
This is fixed in our latest daily builds. Increased to 1 second max zoom. In the future, I will be allowing even more zoom, and possibly a frame-by-frame display once you get super zoomed in. =)

![maxzoom](https://cloud.githubusercontent.com/assets/5551883/19337672/d35a8b82-90dc-11e6-93f8-7e1337f621e0.png)

**Comment by SlimeQ** [comment]
i'd maintain that 1s is still sort of ridiculous for anything but sloppy cuts. why is there even a limit in the first place? Why can't I change it in the preferences?

**Comment by silvascientist** [comment]
Yeah I'm sorry fam but 1 sec still isn't gonna cut it. Having to scout other editors atm.

Signed,
Dude from 2020 wondering why you still haven't fixed this

**Comment by N3WWN** [comment]
@silvascientist What is the use case for needing more than 1s per division on the timeline?  

If it's for aligning clips, you can easily align within a frame or so with the 1s/div zoom level and then use the nudge (<kbd>Shift</kbd>+<kbd>Left</kbd> and <kbd>Shift</kbd>+<kbd>Right</kbd>) if it's not in perfect alignment.  

Also, since the original issue was addressed, resolved and closed in 2016, it would be helpful if you could open a new ticket with context and details on why additional zooming is required for your use.  

FYI, adding comments to closed issues does not reopen the issue, so the comments are likely to get lost when devs are looking at open issues to work.

Thanks!

**Comment by jakewagner02** [comment]
Yeah this is difficult. the difference between .29 and .30 is what I need. I am trying to sync up the video of a rhythm guitar with a solo, and it is ever so slightly off. I need to be right in the middle.

**Comment by ferdnyc** [comment]
@jakewagner02 Yeah, OpenShot isn't the best at adjusting things "in between" frames -- being able to zoom in closer wouldn't change that, which is one of the reasons we've always been resistant to those requests. I think people imagine it would enable them to do more things than it actually would, in practice.

You _can_ actually perform half-frame "nudges" of a clip using the keyboard. The default bindings are <kbd>Shift</kbd>+<kbd>←</kbd> and <kbd>Shift</kbd>+<kbd>→</kbd>. You can _try_ that and see if it helps you get things better aligned.

But if it **doesn't**, you may have better luck bringing your audio into Audacity and adding/trimming samples at the start of the file, shifting it ever so slightly over so that it better aligns with the frame rate of your video. Then you can write that back out to a WAV file and import it into OpenShot. You'll be able to align things much more precisely that way, though of course it may require a bit of trial-and-error since you're effectively attempting to do a carpenter's measure-and-cut with the waveform taken completely outside of the project for modification.

**Comment by zephyr707** [comment]
you can add in more entries below 1 second for zoomSeconds:

```
/usr/lib/python3/dist-packages/openshot_qt/classes/conversion.py`

zoomSeconds = [0.01, 0.1, 0.25, 0.33, 0.5, 1, 3, 5, 10, 15, 20, 30, 45, 60, 75,
               90, 120, 150, 180, 240, 300, 360, 480, 600, 720,
               900, 1200, 1500, 1800, 2400, 2700, 3600, 4800, 6000, 7200]
```

would be nice if this was a user editable pref in the program
