### ISSUE TITLE
FPS is not accurate

### ISSUE THREAD

**Issue by ashmetry** [OpenShot/openshot-qt#3138]
FPS is not accurate. Selecting for example 30 fps will generate 30.xx in the final video. This causes problems with services only accepting videos with specific FPS quality.

**Steps to reproduce the behavior:**
Steps I took: 

1. Download a sample video:  I used this: https://www.sample-videos.com/video123/mp4/720/big_buck_bunny_720p_1mb.mp4
2. Dragged the video to the timeline. 
3. Export Video (these are the settings I used: https://a.cl.ly/E0uE4pkb)
4. The final video is 30.19 f/s see https://a.cl.ly/KouelXPP when it should be 30

**Expected behavior:**

**System Details:**
- OpenShot Version 2.4.4
- Operating System / Distro: Windows 10

**Comment by SuslikV** [comment]
Transcoding only or some heavy editing?

**Comment by ashmetry** [comment]
No editing whatsoever. Here are the steps I took: 

1.Download a sample video:  I used this: https://www.sample-videos.com/video123/mp4/720/big_buck_bunny_720p_1mb.mp4
2. Dragged the video to to the timeline. 
3. Export Video (these are the settings I used: https://a.cl.ly/E0uE4pkb)
4. The final video is 30.19 f/s see https://a.cl.ly/KouelXPP

**Comment by SuslikV** [comment]
Cannot reproduce this with the one of the latest _Daily Builds_ ( https://www.openshot.org/download/ ). Can you give it a try?

**Comment by ashmetry** [comment]
I checked it again using the latest build and I still see the problem. See
video:  https://a.cl.ly/mXum1Rdr Notice that the final file is 30.19 f/s
when it should be 30. Audio is 48K as it should be.

**Comment by SuslikV** [comment]
Can you share the exported file as well?

**Comment by ashmetry** [comment]
You can find both files here: https://a.cl.ly/jkune79q

**Comment by SuslikV** [comment]
The file has constant FPS. Deltas is 159 samples of 512 deltas + last one at 0 delta for video, and 249 samples of 1024 deltas for audio  - thus only two constant values but the last sample. No other variations is present. I not quite sure how Windows properties calculates the fps field for now. But the samples are OK in terms of constant fps and the last ISO I have seen for MP4 format. Am I wrong?

_Some info._
output:
video
track timescale = 15360
track duration = 81408
thus track's duration is 5.3 sec

audio
track timescale = 48000
track duration = 254976
thus track's duration is 5.312 sec (the longest track = the length of the movie)

It looks like current version of the Windows simply takes the length of the video track (5.3 sec) and total number of the video samples (160) to calculate the FPS.

@ashmetry 
1) Is this causes any real difficulties when you importing the file to some service?
2) Just for the experiment, can you say what corresponding Windows field says about the next file sample? - it was created using other software (OBS Studio), 
[1280x720_444_709_tv_10sec_10sec.zip](https://github.com/OpenShot/openshot-qt/files/3996410/1280x720_444_709_tv_10sec_10sec.zip)
3) What build of the OpenShot you actually used for the posted exported file (in the .zip)? It has no _faststart_ swap of the indexes tables for mp4. Did you made some changes to the source of the OpenShot or just posted the output file from the old setup? (it has nothing to do with the issue itself but I'm just wondering why it is not working for you)

**Comment by ashmetry** [comment]
I am not an expert about this but I do know that when I submitted to one of
amazon services, it was rejected because the fps was not exactly 30. After
I converted it using VLC it was accepted. Here is the converted file after
VLC conversion and this is compare of both files FPS.
https://a.cl.ly/qGuDXz9e converted file: https://a.cl.ly/o0uQEQbq The rate
is different but you can clearly see that the frame rate is exactly 30 in
the converted file vs the file produced by OpenShot is 30.19 and not 30

**Comment by SuslikV** [comment]
@ashmetry the technical info is not for you personally. I just using the site to inform other developers who may find something new.

@ashmetry Anyway, can you give the answer to other two questions as well?

From my point of view if there is problem then it is only in the last encoded video sample created by _libopenshot_ lib. The posted `Untitled Project-converted.mp4` has 1 sample of 2999 delta + 153 samples of 3000 delta for video, and 236 samples of 1023, 1024, 1025 deltas for audio (all values cycled in row and each last for 1 sample):

video
track timescale = 90000
track duration = 461999
thus track's duration is 5.13332(2) sec (the longest track = the length of the movie)

audio
track timescale = 48000
track duration = 241663
thus track's duration is 5.03464583(3) sec

Thus the 5.13332(2) sec / 154 (total video samples) possibly truncated to 0.03333 ms of about 30 fps.

The deviations in video fps is small in both cases. The standard I mentioned earlier is ISO/IEC 14496-12 edition 2015. There was info:

>The time to sample boxes must give non‐zero durations for all samples with the possible exception of the last one. Durations in the `stts` box are strictly positive (non‐zero), except for the very last entry, which may be zero. This rule derives from the rule that no two time‐stamps in a stream may be the same. Great care must be taken when adding samples to a stream, that the sample that was previously last may need to have a non‐zero duration established, in order to observe this rule. If the duration of the last sample is indeterminate, use an arbitrary small value and a `dwell` edit.

That means that the `Untitled Project-converted.mp4` (that has the **first** sample aside of the others by the 1/90000 sec) is actually not constant fps and the file mentioned in the issue is actually comply to the mp4 rules. Is it has variable frame rate? In my point of view - No.

Is the mentioned Amazon service is free? (to test with)

**Comment by ashmetry** [comment]
Thanks for your input. Unfortunately it’s part of a bigger service on
amazon that is not free. (Amazon video advertising network).  I agree that
the deviation is minimal but the final result according to Windows is still
not exactly 30fps. I appreciate your input and hard work on this.

**Comment by SuslikV** [comment]
Hope, Windows will change it back to the Win7 result - where it shows no variable fps for this file.

Still waiting for the answer on the two other questions.

**Comment by ferdnyc** [comment]
@SuslikV 
> What build of the OpenShot you actually used for the posted exported file (in the .zip)? It has no faststart swap of the indexes tables for mp4. 

The OP says OpenShot 2.4.4, I assume that means 2.4.4 release. Didn't faststart go in after the release?

**Comment by SuslikV** [comment]
@ferdnyc Release version? It always in few steps off of the daily build. Maybe you are right. I totally forgot about the release version.

**Comment by jonoomph** [comment]
This is fixed in the daily build I believe. Closing issue for now.

**Comment by cohlar** [comment]
@jonoomph I still experience the same issue on version 2.5.1. As a result I am unable to upload the video to Amazon.

**Comment by JacksonRG** [comment]
@cohlar were you using a daily build?

**Comment by greytexture** [comment]
Can we please reopen this bug? Since it's not fixed. Or do I need to submit it again? It really can't be Windows fault since it happens only with OpenShot.
