### ISSUE TITLE
Import Files dialog not working in latest Daily Build

### ISSUE THREAD

**Issue by USATechDude** [OpenShot/openshot-qt#3774]
**Describe the bug:**
When I try to import files using the "+" button on the toolbar, the File >> Import Files menu option, or the CTRL+F or Command+F keyboard command, nothing happens in Windows, macOS, or Linux on the latest Daily Build (OpenShot-v2.5.1-dev2-1602940205-49b7e623-78db4b94)

**Steps to reproduce the behavior:**
1. Launch OpenShot
2. Click the "+" button in the toolbar
3. Click the File menu then click Import Files
4. Press CTRL+F or Command+F
5. Nothing happens
6. Drag-and-drop from Windows Explorer, Finder and File Manager still works

**Expected behavior:**
I should be able to use the menu options or the keyboard command to import files.

**System Details:**
- OpenShot Version: OpenShot-v2.5.1-dev2-1602940595-49b7e623-78db4b94-x86_64.dmg
- OpenShot Version: OpenShot-v2.5.1-dev2-1602940205-49b7e623-78db4b94-x86_64.exe
- OpenShot Version: OpenShot-v2.5.1-dev2-1602940103-49b7e623-78db4b94-x86_64.AppImage
- Operating System / Distro: macOS Catalina Version 10.15.7
- Operating System / Distro: Windows 10 Version 10.0.19041.572
- Operating System / Distro: Debian 10.6 [4.19.0-11amd64 (2020-09-17)]

**Log Files:**
OpenShot does not crash.

**Exception / Stacktrace:**
OpenShot does not crash and there is no strange output

**Screenshots:** (Optional)
No screenshots available

**Comment by ferdnyc** [comment]
@USATechDude 

Hmmm. Well, that's gotta be #3630, let me see what I did there. Thanks for reporting.

**Comment by ferdnyc** [comment]
Dumb mistake, I left out an import. So odd that Codacy doesn't catch that.

Anyway, should be fixed in the next set of builds.

**Comment by USATechDude** [comment]
@ferdnyc Your changes are working in macOS, but I still cannot access the Import Files dialog in Windows or Linux.

**Comment by ferdnyc** [comment]
@USATechDude Hmm. Well, that makes _no_ sense. Let me dig into what might be going on there a bit more...

(FYI, if you're interested, on Linux the AppImage files can be executed from a terminal window — literally just execute the file as a shell command — to see the OpenShot console output "live" while it's running. For example:
```sh
[username@host dir]$ cd /path/to/download
[username@host dir]$ ./OpenShot-v2.5.1-dev2-1603083818-49b7e623-78db4b94-x86_64.AppImage
Loaded modules from: /tmp/.mount_IWMeiX/usr/bin
INFO app: ------------------------------------------------
INFO app:             Mon Oct 19 07:03:59 2020            
INFO app:               Starting new session              
INFO app: ------------------------------------------------
INFO app:          OpenShot (version 2.5.1-dev2)          
INFO app: ------------------------------------------------
INFO app: openshot-qt version: 2.5.1-dev2
INFO app: libopenshot version: 0.2.5-dev2
INFO app: platform: Linux-5.8.13-200.fc32.x86_64-x86_64-with-fedora-32-Thirty_Two
INFO app: processor: x86_64
INFO app: machine: x86_64
INFO app: python version: 3.6.9
INFO app: qt5 version: 5.9.5
INFO app: pyqt5 version: 5.10.1
INFO language: Qt Detected Languages: ['en-US']
INFO language: LANG Environment Variable: en_US.utf8
INFO language: LOCALE Environment Variable: 
INFO language: OpenShot Preference Language: Default
```
(...and eventually...)
```
ERROR exceptions: Unhandled Exception
Traceback (most recent call last):
  File "/tmp/.mount_IWMeiX/usr/bin/windows/main_window.py", line 765,
 in actionImportFiles_trigger
    QUrl.fromLocalFile(recommended_path))[0]
TypeError: getOpenFileUrls(parent: QWidget = None, caption: str = '',
 directory: str = '', filter: str = '', initialFilter: str = '',
 options: Union[QFileDialog.Options, QFileDialog.Option] = 0,
 supportedSchemes: Iterable[str] = []): argument 3 has unexpected type 'QUrl'
```
Hrm. I think this is possibly a bug in older PyQt. The third `getOpenFileUrls()` argument (`directory`) is most definitely _supposed_ to be a `QUrl`, but looks like PyQt 5.10 maps it to the Python string type.

PyQt 5.14.2 on my Fedora 32 box has it right:

```text
$ pydoc3 PyQt5.QtWidgets.QFileDialog.getOpenFileUrls
Help on built-in function getOpenFileUrls in PyQt5.QtWidgets.QFileDialog:

PyQt5.QtWidgets.QFileDialog.getOpenFileUrls = getOpenFileUrls(...)
    getOpenFileUrls(parent: QWidget = None, caption: str = '',
 directory: QUrl = QUrl(), filter: str = '', initialFilter: str = '',
 options: Union[QFileDialog.Options, QFileDialog.Option] = 0,
 supportedSchemes: Iterable[str] = []) -> Tuple[List[QUrl], str]
```

I'll see what I can do.

**Comment by ferdnyc** [comment]
Heh, yup. A PyQt bug that was only fixed a year ago in PyQt 5.13, according to [the Changelog](https://www.riverbankcomputing.com/static/Downloads/PyQt5/ChangeLog-5.15.2.dev2010041344):

```
2019-09-05  Phil Thompson  <phil@riverbankcomputing.com>

	* PyQt5.msp:
	Fixed the type of the directory argument to the getOpenFileUrl(),
	getOpenFileUrls() and getSaveFileUrl() methods of QFileDialog.
	[fdd9e3fa43e6] <5.13-maint>
```

I'll add some sort of version test so OpenShot can decide which one to use.

**Comment by ferdnyc** [comment]
![giphy](https://user-images.githubusercontent.com/538020/96459411-16f65e00-11f0-11eb-8bf9-91292460fb22.gif)

**Comment by USATechDude** [comment]
@ferdnyc Umm...  This is the error I receive when I try to launch the program in Windows 10.

![Screenshot01](https://user-images.githubusercontent.com/65924242/96462145-d6e0ac80-11ea-11eb-9a73-462a640ab348.png)

Linux tested fine and the macOS DMG file is not yet available.

**Comment by USATechDude** [comment]
I just tested the Import Files dialog on macOS and all functions worked as expected.

**Comment by ferdnyc** [comment]
@USATechDude  Yeah, sorry, for some reason Windows cx_Freeze is failing to freeze the `distutils` module. In fact when I tried to manually add it to the package list, it broke the entire Windows build. So, I've switched to a more hackish workaround that doesn't require `distutils.version`. It's running on the project builders now, if it's successful I'll open a PR and get that fixed up.

**Comment by ferdnyc** [comment]
Just merged #3777, should be fixed now.

"For SURE, for sure!",  I guess? (Best not to press my luck, I figure.)

**Comment by USATechDude** [comment]
@ferdnyc I just downloaded and installed the latest Daily Build in Windows, but I still receive the same error message.  ☹️ 

![Screenshot01](https://user-images.githubusercontent.com/65924242/96614453-c3eeda80-12c5-11eb-8375-604805a54f2d.png)

**Comment by ferdnyc** [comment]
@USATechDude 

This will hopefully do the job:

https://github.com/OpenShot/openshot-qt/releases/download/daily/OpenShot-v2.5.1-dev2-1603140921-07a447c9-78db4b94-x86_64.exe

**Comment by ferdnyc** [comment]
(I had removed the _need_ for `distutils`, but I forgot to actually **remove** `distutils`.)

**Comment by USATechDude** [comment]
@ferdnyc Nope, that link is to the previous build. 😁  I downloaded [OpenShot-v2.5.1-dev2-1603217539-07a447c9-78db4b94-x86_64.exe](https://github.com/OpenShot/openshot-qt/releases/download/daily/OpenShot-v2.5.1-dev2-1603217539-07a447c9-78db4b94-x86_64.exe) and tested this version and I am happy to say that it works!

Thank you for all of your hard work and help! 🎉 🎆 🥳

**Comment by ferdnyc** [comment]
Ah, I guess the website hadn't updated yet. (I can't believe it's the 20th already! Almost the 21st, now.)

Thanks for confirming, sorry about all the confusion there.
