### ISSUE TITLE
Moving Clip in Track does not update in time line

### ISSUE THREAD

**Issue by smittie** [OpenShot/openshot-qt#5187]
**Describe the bug:**
Time line and Preview play do not update to reflect changes made to clip in track.

**Steps to reproduce the behavior:**
1. Drag clip to track butted to previous clip on same track
2. Remove some amount of newly placed clip from between the previous clip and the newly placed clip such that there is blank space between the new clip and the previous clip.
3. Move the new clip so that it butts to the previous clip

**Actual Result**
In the Timeline the space remains. In preview the space remains. The changes made in the track are never reflected in the Timeline or in preview play.

**Expected Result**
Changes in the track should be reflected in the Timeline and in preview and in the export.

**System Details:**
Loaded modules from: /usr/lib/python3/dist-packages/openshot_qt
INFO app: ------------------------------------------------
INFO app:             Wed Apr  5 10:49:51 2023            
INFO app:               Starting new session              
INFO app: ------------------------------------------------
INFO app:             OpenShot (version 3.0.0)            
INFO app: ------------------------------------------------
INFO app: openshot-qt version: 3.0.0
INFO app: libopenshot version: 0.3.0
INFO app: platform: Linux-5.15.0-69-generic-x86_64-with-glibc2.35 (Linux Mint 21.1)
INFO app: processor: x86_64
INFO app: machine: x86_64
INFO app: python version: 3.10.6
INFO app: qt5 version: 5.15.3
INFO app: pyqt5 version: 5.15.6
INFO project_data: Setting profile to HD Vertical 720p 30 fps
INFO project_data: Apply default audio playback settings: 44100, 2 channels
INFO app: checking babl_ext_path: /usr/lib/python3/dist-packages/openshot_qt/lib/babl-ext

OpenShot-QT installed and updated from openshot_developers-libopenshot-daily-jammy.list

**Log Files:**
Nothing interesting in libopenshot.img.
openshot-qt.log attached.

**Screenshots:** (Optional)
Annotated screenshot shows playhead in an open space in the Timeline which is not what is shown in Track 1. Preview screen is blank. 

![OpenShot Screenshot for Bug #5187](https://user-images.githubusercontent.com/12665975/230149300-50b181c9-e4c9-418a-9dee-57b6e540d889.png)

**Comment by smittie** [comment]
This bug blocks production work for my company.

**Comment by Colorjet3** [comment]
Hello @smittie.  I just tried to replicate this issue in Linux Mint 21 with v3.0.0- and v3.1.0- (this is a new release-candidate getting ready to be published as production release) and was Not able to replicate your issue.  I ran the AppImage for both versions to test with.

I have a few questions and suggestions:
1.  Does this happen in all projects or just this one?
2.  Does this happen if you start a new project?
3.  What happens if you remove the clips from the timeline, save the project, drag the files again onto Track 1 and do the same steps?  Does the problem persist?

Try this with v3.0.0 first:
5.  Close Openshot if running.
6.  Make a backup of /home/username/.openshot_qt folder.
7.  Delete /home/username/.openshot_qt folder.
8.  Start Openshot and see if the issue persists.  You should try your existing project and start a new project.

Try this with v3.1.0:
1.  Go to openshot.org/download/#daily.
2.  Get the latest available of v3.1.0-release-candidate AppImage.
3.  Make a backup of /home/username/.openshot_qt folder.  You can skip this if you already made a backup.
4.  Start Openshot and see if the issue persists. You should try your existing project and start a new project.

Let me know and we can continue troubleshooting if needed.

**Comment by smittie** [comment]
Fresh install from the Stable PPA works as expected.

**Comment by Colorjet3** [comment]
That sounds great and good luck with your projects.

**Comment by smittie** [comment]
> 1. Does this happen in all projects or just this one?

Checking.

> 2. Does this happen if you start a new project?

Checking.

> 3. What happens if you remove the clips from the timeline, save the project, drag the files again onto Track 1 and do the same steps?  Does the problem persist?

Yes. Removing the clip from the Track does remove the clip from the Timeline but the bug is reproducible when I try to put any clip back in the Track in the same way.
 
> Try this with v3.0.0 first: 5. Close Openshot if running. 6. Make a backup of /home/username/.openshot_qt folder. 7. Delete /home/username/.openshot_qt folder. 8. Start Openshot and see if the issue persists. You should try your existing project and start a new project.

Done. Bug still repros.

> Try this with v3.1.0:
> 
> 1. Go to openshot.org/download/#daily.
> 2. Get the latest available of v3.1.0-release-candidate AppImage.
> 3. Make a backup of /home/username/.openshot_qt folder.  You can skip this if you already made a backup.
> 4. Start Openshot and see if the issue persists. You should try your existing project and start a new project.

Did not try 3.1.0 candidate unless that is what is delivered through the daily PPA. I am now working with the same project file on whatever is delivered through the Stable PPA where the bug is not reproducible, at least so far.

> Let me know and we can continue troubleshooting if needed.

My solution for now is to revert back to the Stable release. I will go back to working on this bug as soon as I can.

I understand that we need a reproducible case. Does it matter if that reproducible case requires using specific video files that I am willing to provide?

**Comment by smittie** [comment]
Where is the 3.1.0 candidate?

**Comment by smittie** [comment]
Uh, going back to an older version of the software qualifies as a resolved issue?

**Comment by Colorjet3** [comment]
You can find v3.1.0 [here](https://www.openshot.org/download/).

**Comment by smittie** [comment]
The 3.1.0 release candidate is not what is installed through the daily builds PPA?

**Comment by smittie** [comment]
Using same project file, same video files this bug does not reproduce on the OpenShot-v3.0.0-x86_64.AppImage.

I think I need to understand what the differences are between the App Image builds (which I prefer not to use for production work), the daily builds PPA and the Stable PPA. It seems like the App Image is the most stable and reliable.

**Comment by smittie** [comment]
I will understand if you close the bug at this point.

**Comment by Colorjet3** [comment]
Hi @smittie.  I am primarily a Windows user and very novice Linux user.  I merely test and often found the AppImage to be the most stable.  What I do know is that each Linux flavor/project has their own timeline of introducing newer versions of an application via however they package (software manager, flatpack, PPA, etc....and don't ask me about the differences).

Here are some of the answers to your questions (these answers are from questions I had posed to the dev team):
1.  When using the PPA installation you can only have a single software installation of Openshot.  Meaning if you run the Stable PPA then run the Daily PPA they will trump each other.  Meaning they both install in the same folder.
2.  To completely uninstall you can run:  sudo apt-get remove openshot-qt python3--openshot
3.  You can also uninstall using the package manager / software store.
4.  Most Linux distros come with a unique software channel for that specific distro release.  The software in those channels is "frozen" at the time of the distros release and thus, usually old, including Openshot.  This is where using the PPA installation will provide you to download the latest production release (in this case, v3.0.0-release-candidate) or the latest DEV Daily Build available.
5. Regardless of how you install it or which version you run they all share ~/.openshot_qt folder.
6. What I know about the AppImage is that it is a self contained package not dependent on the operating system having any of the supporting files/tools for Openshot to run - I have seen exceptions to this.  Also, I know that the AppImage currently does not support Hardware Acceleration and not sure if it ever will.

My apologies if I provided answers that you already knew.  I am merely sharing what answers I have.  If you need more specific questions I will need to escalate this to one of the IT support guys.

**Comment by Colorjet3** [comment]
**Update:**  I just installed Openshot, in Linux Mint 21, using the Daily PPA commands and it installed v3.0.0.  My expectation was that I would get v3.1.0-release-candidate.  I just posted my question to the DEV team to see if this is how it is supposed to be or there is some other issue.

**Comment by smittie** [comment]
Thank you for the response. I appreciate it.

With regard to PPA versions, I always do a complete removable including settings and cache when switching between versions (Stable PPA vs Daily PPA) or when running an AppImage version.

To completely uninstall software apt purge openshot-qt python3-openshot is the better choice. It should be noted that this will leave behind ~/.openshot-qt and ~/.cache/openshot directories. If an issue is being caused by something in the QtWebEngine or openshot.settings, only running apt purge may not be enough.

The apt purge/remove command will only work on linux Distros that are based on Debian.

**Comment by smittie** [comment]
> **Update:** I just installed Openshot, in Linux Mint 21, using the Daily PPA commands and it installed v3.0.0. My expectation was that I would get v3.1.0-release-candidate. I just posted my question to the DEV team to see if this is how it is supposed to be or there is some other issue.

Thank you.

**Comment by smittie** [comment]
> **Update:** I just installed Openshot, in Linux Mint 21, using the Daily PPA commands and it installed v3.0.0. My expectation was that I would get v3.1.0-release-candidate. I just posted my question to the DEV team to see if this is how it is supposed to be or there is some other issue.

Regarding this, I have looked through as many places as I can find and have not found this. It would be extremely useful if a build number and/or build date were incorporated somewhere. I expected to find it when launching OpenShot-QT from the command line but it does not appear to be there.

**Comment by Colorjet3** [comment]
Thank you @smittie for the cleanup command.  Yes, in all the different operating systems, the ~/.openshot_qt folder stays intact as there can be user specific files that need to be retained...this includes the Recovery folder that can be critical if a project gets corrupted.  I wasn't aware of the ~/.cache/openshot directories....I am wondering if this exists in Windows environment as well.

Running the Daily PPA installation and AppImage, I am able to perform Help | About Openshot and seed the version number.  Is this not the case for you?

By the way, in all of these discussions I lost track of your original issue with the the track and the timeline update.  Is this now resolved?

**Comment by smittie** [comment]
**Additional Info**

Installed OpenShot-QT from the Daly PPA after deleting ~/.openshot-qt and ~/cache/openshot
Verified that this issue was still reproducible.
Removed OpenShot-QT using apt purge openshot-qt python3-openshot
Also ran apt autoremove
Verified that ~/.openshot-qt and ~/cache/openshot had not been deleted
Switched PPA to Stable
Installed OpenShot using apt install openshot-qt python3-openshot
Was able to reproduce this issue on OpenShot Stable.
Manually deleted ~/.openshot-qt, did not delete ~/cache/openshot
Was NOT able to reproduce this issue.

Same result if I just  do a save in OpenShot Stable.

Attached are the settings files from the Repro and Non-Repro states in case that is interesting.
[5187_Repro_libopenshot.log](https://github.com/OpenShot/openshot-qt/files/11162607/5187_Repro_libopenshot.log)
[5187_Repro_openshot.settings.txt](https://github.com/OpenShot/openshot-qt/files/11162608/5187_Repro_openshot.settings.txt)
[5187_Repro_openshot-qt.log](https://github.com/OpenShot/openshot-qt/files/11162609/5187_Repro_openshot-qt.log)
[5187_No-Repro_libopenshot.log](https://github.com/OpenShot/openshot-qt/files/11162613/5187_No-Repro_libopenshot.log)
[5187_No-Repro_openshot.settings.txt](https://github.com/OpenShot/openshot-qt/files/11162614/5187_No-Repro_openshot.settings.txt)
[5187_No-Repro_openshot-qt.log](https://github.com/OpenShot/openshot-qt/files/11162615/5187_No-Repro_openshot-qt.log)

**Comment by Colorjet3** [comment]
Thank you for all that.  So, after deleting the ~/.openshot_qt and ~/cache/openshot the issue was resolved.  Just wanting to confirm.

**Comment by smittie** [comment]
I can use what is installed from the Stable PPA to work around this issue. It is still reproducible on what is installed from Daily PPA.

On builds coming from Daily PPA, there is a version number in the About dialog. However, I have not found a way to differentiate between Daily builds. The version is not changed in builds that get posted to the Daily PPA which makes sense. I wouldn't expect it to. But it would be useful to be able to know which daily build one is running.

**Comment by smittie** [comment]
> Thank you for all that. So, after deleting the ~/.openshot_qt and ~/cache/openshot the issue was resolved. Just wanting to confirm.

Only deleted ~/.openshot_qt. However, saving in the stable build also clears the problem. Without knowing any code paths, it appears that there might be some indication of the issue in the openshot.settings file. Just my guess.

**Comment by Colorjet3** [comment]
Thank you @smittie.  I am going to keep this posting Open for now as I have some follow up questions with the dev team regarding the Daily PPA installation and version numbers.

**Comment by smittie** [comment]
Thank you, @Colorjet3. I know I'm new here but, should that be tracked under it own bug? The PPA Vers question.

**Comment by Colorjet3** [comment]
It will most likely be tracked separately.  I just need to hear back from the dev team.  Ultimately they will decide what the next steps are and how to track it.

**Comment by Colorjet3** [comment]
Hello @smittie.  Here is the response from @jonoomph (product owner/lead developer) regarding the version numbers:

"The version # in the PPA is set by the Debian packaging branch in Git (it's a bit complicated)... so the version # stays the same until after a release - when I manually update it to "3.1.0" (in this case)

Now that our testing of 3.1.0 release candidates has settled down and stabilized - I am going to publish the release's source code to GitHub for 3.1.0, and start working on my release Blog Post and summarizing the release notes. The official "go live" is not today - but will be very soon"

Actually, v3.1.0 was released today and should be available via the PPA Stable installation.

Please let me know if you have any other questions regarding this thread.  If not, feel free to close this ticket or I can do it as well.

**Comment by Colorjet3** [comment]
Hello @smittie.  The official v3.1.0 has been released and according to @jonoomph the Linux PPA is now updated with 3.1.0 for both daily PPA and stable PPA.
