### ISSUE TITLE
Cannot drag files from the project files window into timelines

### ISSUE THREAD

**Issue by andreagangemi** [OpenShot/openshot-qt#5221]
**Describe the bug**
I cannot drag my videos in project files into the timeline on Ubuntu 23.04
This behaviour has been noticed only on my laptop running ubuntu 23.04 with low latency kernel.
instead it works on my other PCs running Ubuntu 22.04LTS and Windows 10

**Steps to reproduce the behavior:**
1. left click on a video on the project file windows
2. by keeping the left button pressed, drag the file into the timeline

**Expected behavior**
One over the timeline the pointer icon should change showing a "+" instead the pointer shows a denial symbol

**System Details**
- OpenShot Version: 3.1.1
- libopenshot Version:  0.3.2
- Platform: Linux-6.2.0-1003-lowlatency-x86_64-with-glibc2.4
- Processor: x86_64
- Machine: x86_64
- Python version: 3.8.10
- Qt5 version: 5.12.8
- PyQt5 version: 5.14.1
- Qt Detected Languages: ['en-US']
- LANG Environment Variable: en_US.UTF-8
- LOCALE Environment Variable: 
- Daily Build: Verified issue still exists in daily build: http://github.com/OpenShot/openshot-qt/releases/download/OpenShot-v3.1.1-daily-11406-8ab0cb4c-75076545-x86_64.AppImage

**Log Files**
- [openshot-qt.log](https://s3.amazonaws.com/logs.openshot.org/t54r4mwevjmamwuoc2471alsrryjxom0/openshot-qt.zip) (290 KB)
- [libopenshot.log](https://s3.amazonaws.com/logs.openshot.org/t54r4mwevjmamwuoc2471alsrryjxom0/libopenshot.zip) (25 KB)

**Exception / Stacktrace**
```No stacktrace found in log files```

**Screenshots** (Optional)
If applicable, add screenshots to help explain your problem. You can include screenshots by
copy/pasting them on GitHub or dragging-and-dropping into the GitHub page. All images are public,
so please don't post screenshots containing personal information.

**Comment by Colorjet3** [comment]
Hello @andreagangemi.  Before we dive into the issue I want to let you know that I have never been able to drag a file from the "Project Files" window by right clicking the mouse and keep pressing it and then dragging it.  I just tried it in Ubuntu 22.04, 22.10, and 23.04.   I see that I am able to do it in Windows.  However, 100% of the time, when I right click on a file in the "project files" windows, I get the menu that has many options to select from that applies to that specific file.

**Note:**  I am assuming that you are right handed and have not switched your mouse click functions.  Meaning left click is left click and right click is right click.

1.  How did you install Openshot v3.1.1?
2.  Did you try using the left mouse click to select a file in the "Project files" window and drag it to the timeline?  Did this work?

**Comment by ric355** [comment]
I have the same issue on Ubuntu 23.04. I think the original poster means left click. I tried the 3.1.1 app image and it is the same. 

The problem extends to effects as well. I am currently trying to drag the crop effect to the timeline and it is being denied. So I think it is going to be all drag functions, not specific to project files.

It is possible to add a project file to the timeline by right clicking on it and using the "Add to timeline" option. However, no parallel function exists for effects.

**Comment by ric355** [comment]
A bit more information that might suggest where to look for this.

I tried using Wayland as there are a couple of oddities going on with the window manager in Ubuntu 23 compared to 22. The most notable is that if you click on a window caption it doesn't bring the window to the front unless you drag the mouse, or specifically click on the window border. If you click inside the window it does come to the front without needing to drag the mouse first. On Wayland it works as it always used to; clicking the caption just brings the window to the front as you'd expect.

So I tried running OpenShot on Wayland to see if it affected the drag target but unfortunately something more significant is occurring and the entire timeline is not drawn at all, so I couldn't test it that way.

I therefore started looking for another video editor and picked kdenlive. Surprisingly (perhaps not!) it also has the *same* drag drop issue i.e. the drag target is denied when you try to drag a clip to the timeline. I then logged in with Wayland and tried kdenlive again, and lo and behold the drag functionality works as expected.

So I'd conclude that something has changed in Ubuntu 23's standard window manager that is causing the drag target to be denied.

**Comment by andreagangemi** [comment]
> Hello @andreagangemi. 


First of all I apologize, I was meaning "left", I corrected the post. Sorry for the mistake.

>     1. How did you install Openshot v3.1.1?

I used appimage

**Comment by Colorjet3** [comment]
Hello @andreagangemi No worries and thank you for updating your post. I am still unable to replicate this issue in Ubuntu 23.04.  I am running Ubuntu in Oracle Virtualbox.  I am a novice Linux user and need to escalate this to the Openshot development team to look into this issue.

@ric355 - Thank you also for all the additional information you provided.  I am sure this will help the Openshot dev team to better troubleshoot the issue in hopes of finding a resolution.

**Comment by andreagangemi** [comment]
A little extra note from my side, maybe it can help:
my Ubuntu 23.04 is not a fresh installation but an upgrade from 22.10,
When I noticed the issue I tried to reset my desktop by running
`dconf reset -f /org/gnome/`

unfortunately with no results

**Comment by ric355** [comment]
Mine is also an upgrade from 22.10, but in my case I have also tried a fresh installation of Ubuntu 23 (using VMWare), and the problem is still there.

**Comment by ric355** [comment]
More information. Once you have added something to the timeline, it *is* possible to drag it around the timeline and drag it between tracks. So the scenario when it doesn't work is if the source and target areas (windows?) are different.

**Comment by andreagangemi** [comment]
Yes, once the item is in the timeline I can drag it between tracks.
The issue seems related to dragging from different areas, I also verified I
cannot drag an effects, emojis or transitions.



Il sab 29 apr 2023, 09:16 ric355 ***@***.***> ha scritto:

**Comment by Colorjet3** [comment]
An internal Bug ticket has been created to look into this issue.

**Comment by ninstar** [comment]
It is actually an issue with mutter in Gnome 44, which is affecting all applications that uses Qt.

**Comment by ric355** [comment]
> It is actually an issue with mutter in Gnome 44, which is affecting all applications that uses Qt.

Do you know if there is an issue raised in the mutter repo for it?

**Comment by ric355** [comment]
Is this it?

https://gitlab.gnome.org/GNOME/mutter/-/issues/2715

**Comment by ninstar** [comment]
> Is this it?
> 
> https://gitlab.gnome.org/GNOME/mutter/-/issues/2715

Yes, but I'm not sure if Ubuntu or Fedora has the fix yet (which I believe to be the two distros most people here are using).

**Comment by ric355** [comment]
> > Is this it?
> > https://gitlab.gnome.org/GNOME/mutter/-/issues/2715
> 
> Yes, but I'm not sure if Ubuntu or Fedora has the fix yet (which I believe to be the two distros most people here are using).

It is definitely not in Ubuntu yet. However, at least it is fixed and I expect will arrive in due course.  I did build mutter from source with the intention of patching it but the unpatched build just crashed when I installed it so I'll wait for the fix to come through.

**Comment by andreagangemi** [comment]
In the meantime as a temporary workaround I changed desktop manager to MATE and it works. Also tried KDE and it works.

**Comment by jonoomph** [comment]
Thanks @andreagangemi for the workaround. This does not seem to be something I can fix in the OpenShot code (based on my research), and unfortunately, we will have to wait for distros to include the fix tagged in this issue: https://gitlab.gnome.org/GNOME/mutter/-/issues/2715. Hopefully, this will be included soon in the major distros, but honestly, I have no real idea when this might be widely released. :cry:

**Comment by jonoomph** [comment]
For those of you looking for a **work-around** on **Ubuntu 23.04**, I was able to compile Mutter from source and verify it fixes the issue reported in this ticket. I did this in a VM (which I was unafraid of breaking... so please proceed only if you understand what the following commands are doing):

Step 1 (Dependencies for Mutter - for Ubuntu 23.04)
===
```
apt install meson \
pkgconf \
cmake \
libgraphene-1.0-dev \
libgtk-3-dev \
gsettings-desktop-schemas-dev \
gnome-settings-daemon-dev \
libjson-glib-dev \
libcolord-dev \
liblcms2-dev \
libxkbfile-dev \
libxkbcommon-x11-dev \
libx11-xcb-dev \
libxcb-randr0-dev \
libxcb-res0-dev \
libgnome-desktop-3-dev \
libgnome-desktop-4-dev \
libcanberra-dev \
libgudev-1.0-dev \
libdrm-dev \
libgbm-dev \
libinput-dev \
libstartup-notification0-dev \
libpipewire-0.3-dev \
xvfb \
libsysprof-4-dev \
gettext \
xcvt \
sysprof \
desktop-file-utils
```

Step 2 (Download Latest Mutter from Git)
===
```
git clone https://gitlab.gnome.org/GNOME/mutter.git
cd mutter
```

Step 3 (Build Mutter from source - and install)
===
```
mkdir build
cd build

meson setup --prefix=/usr --buildtype=debugoptimized -Dtests=false ../
ninja
ninja install
```

Step 4 (Reboot)
===
```
sudo reboot
```

As far as I can tell, this resolves all drag and drop issues with OpenShot on Ubuntu 23.04. But please only use these instructions if you understand what you are doing. :crossed_fingers: :crossed_fingers:

**Comment by ric355** [comment]
> As far as I can tell, this resolves all drag and drop issues with OpenShot on Ubuntu 23.04. But please only use these instructions if you understand what you are doing. crossed_fingers crossed_fingers

I took a risk - all working good.

**Comment by Colorjet3** [comment]
Success!  I just tested these instructions in Ubuntu 23.04 in Oracle VirtualBox environment and drag and drop is working now in Openshot.

I am going to create a new Ubuntu 23.04 without executing this workaround so that when the various distros have the fix out and test that separately.

Thank you @jonoomph!

**Comment by wandrewkeech** [comment]
thank you for the procedure and research on this, resolved my issue (different software, same problem)

**Comment by nitramr** [comment]
Awesome, workaround works for me for another Qt based software... for all Qt based software.

**Comment by ric355** [comment]
Just a heads up. libmutter-12 was updated this morning on my Ubuntu 23 installation alonside a bunch of other stuff such as libre office. The update does not include the fix, so if you are in the habit of accepting updates regularly as I am then you'll have to reinstall the version with the fix in.

If you still have the compiled version from following the procedure above then you only need to run:

```
cd build
ninja install
```

Otherwise you'll need to follow all of the steps above again.

**Comment by Colorjet3** [comment]
Thank you ric355 for the FYI.

**Comment by ric355** [comment]
The fix for this issue has now appeared in the upstream Ubuntu 23 repos.

**Comment by andreagangemi** [comment]
> The fix for this issue has now appeared in the upstream Ubuntu 23 repos.

Sorry for the newbie question: 
does it means that now the issue is fixed on Ubuntu 23.04?

**Comment by ric355** [comment]
> Sorry for the newbie question: does it means that now the issue is fixed on Ubuntu 23.04?

Yes, that is correct. You need to run updates to get it, obviously.
