### ISSUE TITLE
Imported audio stops after 2.30ish...

### ISSUE THREAD

**Issue by cuntymccunt** [OpenShot/openshot-qt#618]
**System Details:** Surface Book Pro
* Operating System / Distro: Microsoft Windows 10
* OpenShot Version: 2.3.1.
* _Please attach log files if crash_

I have imported several audio tracks as MP3s, all with different track lengths, to check, and everyone of them stops after 2.30ish. The file shows as longer and the wave continues (but flat/no audio) for the track length but there is no audio.

**Comment by Sandgolem** [comment]
I am also having this issue. Tried to pull in my podcast for quick editing and I'll be damned if after 2:30 it stops dead

**Comment by sphyrth** [comment]
I think I'm gonna bump this one as well. It's still an issue.
OpenShot 2.4.0
Linux Mint 18.2 32-bit, 4GB RAM

**Comment by DylanC** [comment]
@sphyrth - Yes its definitely an issue worth sorting. I've tagged in all the duplicates.

**Comment by DylanC** [comment]
@sphyrth - I have been notified this has been fixed in the latest daily build. Please try it out.

**Comment by DylanC** [comment]
This is resolved in the latest daily build:
![solved](https://user-images.githubusercontent.com/4488048/31321108-155f4970-ac78-11e7-8783-0439def02c0e.png)

**Comment by sphyrth** [comment]
Dang! Sorry for the late reply. The bug still exists for me.

Since this issue is solved with most of the commenters, I'm going to assume that I did something to break the installation itself.

However, there are similar complaints still popping out. So this problem might be machine-dependent. 

This time, I'm in no hurry because everyone can definitely see the improvements. Thank you OpenShot team!

**Comment by drumm91UWO** [comment]
This bug still exists for me.  I'm running version 2.4.1
