### ISSUE TITLE
Ruler isn't fully drawn if timeline length exceeds maximum canvas pixel dimension (32767px)

### ISSUE THREAD

**Issue by N3WWN** [OpenShot/openshot-qt#652]
**System Details:**
* Operating System / Distro: Fedora 25
* OpenShot Version: OpenShot-v2.3.1-x86_64.AppImage

**Issue Description and steps to reproduce:**
I have a ~35  minute long project and I noticed that the time scale disappears from the top of the timeline under certain conditions:

6sec zoom:  time scale disappears after about 32m45s (1965s = 6 x 327s)
5sec zoom:  time scale disappears after about 27m17s (1637s = 5 x 327s)
4sec zoom:  time scale disappears after about 21m50s (1310s = 4 x 327s)
3sec zoom:  time scale disappears after about 16m22s (982s = 3 x 327s)
2sec zoom:  time scale disappears after about 10m55s (655s = 2 x 327s)
1sec zoom:  time scale disappears after about 5m27s (327s)

It looks like there may be 200 "points" used to display the time scale.  327 seconds would place the "points" from 0 to 65400.  If these points are determined by a 16 bit integer variable, that variable would overflow at 327.675s with a 1s zoom.

I haven't had chance to look at the code, but the solution may be to use a 32 bit integer to store the points.

Let me know if you want any screenshots or additional info.

Thanks!

-Rich

**Comment by sknaumov** [comment]
I saw this problem too on Windows 10 and OpenShow 2.3.1 and 2.3.2.

**Comment by DylanC** [comment]
@N3WWN - Thanks for you feedback. I will take a look at this. Please do provide some screenshots.

**Comment by N3WWN** [comment]
@DylanC 

No problem at all!  I'd love to be able to contribute to the project, but not sure where I could begin.  Do you have a design document that will let me get my head around what the software is doing, all the moving parts (or at least some of them), etc so I can do more than just report issues?

As requested, attached are screenshots showing the issue I'm reporting.

I downloaded a royalty-free video and just placed it on the timeline a bunch of times to get the video length necessary.

1sec zoom: time scale disappears after about 5m27s (327s):
![screen sharing picture september 7 2017 at 09 15 47 edt](https://user-images.githubusercontent.com/19431804/30165200-3d523200-93ad-11e7-9636-6a05687fa9a8.png)

2sec zoom: time scale disappears after about 10m55s (655s = 2 x 327s):
![screen sharing picture september 7 2017 at 09 15 27 edt](https://user-images.githubusercontent.com/19431804/30165203-3d543e92-93ad-11e7-8e24-b23893bb2458.png)

3sec zoom: time scale disappears after about 16m22s (982s = 3 x 327s):
![screen sharing picture september 7 2017 at 09 15 09 edt](https://user-images.githubusercontent.com/19431804/30165202-3d53bd82-93ad-11e7-8262-8751e67da1aa.png)

4sec zoom: time scale disappears after about 21m50s (1310s = 4 x 327s):
![screen sharing picture september 7 2017 at 09 14 49 edt](https://user-images.githubusercontent.com/19431804/30165204-3d573aac-93ad-11e7-8a65-3b54a9847ba8.png)

5sec zoom: time scale disappears after about 27m17s (1637s = 5 x 327s):
![screen sharing picture september 7 2017 at 09 14 32 edt](https://user-images.githubusercontent.com/19431804/30165201-3d537322-93ad-11e7-84e3-00c65f78726e.png)

6sec zoom: time scale disappears after about 32m45s (1965s = 6 x 327s):
![screen sharing picture september 7 2017 at 09 13 55 edt](https://user-images.githubusercontent.com/19431804/30165205-3d5c582a-93ad-11e7-8999-3ac310d82c0d.png)

These were captured with a fresh download of OpenShot-v2.4.0-x86_64.AppImage on the same Fedora 25 system where I first noticed the problem.

Let me know if I can provide any further information or if there is any way that I can get up to speed to contribute directly.

Thanks!

**Comment by DylanC** [comment]
@N3WWN - Thanks, this is great and a very strange bug too. The best way to get started is to email Jonathan about contributing. He should be able to answer all your questions. We could definitely do with some extra help. Even if you can just help test some issues and report back on them.

I would help with the development too but I don't know Python at all.

**Comment by DylanC** [comment]
@N3WWN - Is this still an issue after the #1411 PR?

**Comment by N3WWN** [comment]
@DylanC , 
I can confirm that this bug is still present after #1411 .  The zoom values are different (no 6sec zoom, for instance), but the results are the same.

Here's the ~10m55s timeline disappearance for the 2sec zoom level:

<img width="446" alt="image" src="https://user-images.githubusercontent.com/19431804/39580139-721bdc2e-4eb6-11e8-8682-7da60e6baa4c.png">

Any chance of getting a "BUG" tag on this one?  When I've been looking for things to work on (as time permits), I usually search for that tag.

**Comment by ferdnyc** [comment]
Heh. You know, in all my testing of the zoom code, and even zooming out far enough to discover the 24-hour rollover bug (where the ruler markings goes a little crazy if the visible ruler length is > 24 hours, not that there's any reason it _should_ support that), I never noticed this.

I'll try to see what I can see, too, though I'm worried that this bug may be a bounding-box/widget-sizing issue somewhere in the Angular code. Viewing `src/timeline/index.html` in Chrome is even more broken (it always ends the entire **timeline** at 5 minutes, even when there are clips positioned past that point).

**Comment by ferdnyc** [comment]
Want to hear something hilarious?

[This **exact** bug](https://bugs.launchpad.net/openshot/+bug/722285) was present as far back as OpenShot 1.3.0, reported in Launchpad on 2011-02-20. 

> The timeline only shows the first (320*zoom seeting) seconds of a project.
> So if the zoom slider setting is set to 1 s, the timeline stops at 5'20'' (=320'')
> if it set to 2 s, it stops at 10'40'' (=640''), 4 s it stops at 21'20'' (=1280''), etc.

It somehow survived the complete 2.0 redesign to continue biting us in the ass 7 years later. That is one persistent-ass defect! :rofl:

**Comment by mikelacsa** [comment]
Hey guys, I just want to confirm if this bug still exists?

**Comment by ferdnyc** [comment]
@mikelacsa 

Very much so. Steps to test/reproduce:
1. Import a long video file into OpenShot (I used a 76-minute movie.)
1. Add it to the timeline
1. Select the clip and use Next Marker to jump to the right edge

At 10-second zoom, the ruler markings peter out at `00:54:35:01`, which exactly fits with @N3WWN's observed multiples-of-327 pattern. (54m35s = 3275 seconds; the last visible label marker is at 54m30s which is 3270s.)

**Comment by ferdnyc** [comment]
So, I looked into this some more. By adding a ton of logging to `ruler.js` temporarily, I was able to determine that the drawing function computes all of the correct values for the ruler parameters, goes through _every_ iteration necessary in the loop that draws the tick marks, and computes the correct time index for _every_ tick necessary for it to draw the full length of the ruler.

If I have that 76-minute movie I mentioned placed on the timeline, and I zoom out to 10 seconds, the initial computations produce:
```
timeline_webview:INFO Computed timeline width in pixels: 46294 (based on duration: 4629.4)
timeline_webview:INFO Actual size of track container: 46294
timeline_webview:INFO Defining ruler parameters, tick_pixels: 100 each_tick: 50
timeline_webview:INFO Redrawing ruler, num_ticks: 925.88
```

and the redraw loop logs all the way up to:
```
timeline_webview:INFO Fill text for tick 926: 01:17:10
timeline_webview:INFO Last tick drawn: 927
```

Nevertheless, the ruler stops at 00:54:35, which is tick 655. Anything after that is still computed, its still goes through all the motions, but nothing gets drawn.

![giphy](https://user-images.githubusercontent.com/538020/66443107-c8728900-ea0b-11e9-8320-d0c1c5c5b8a9.gif)

Then I got to thinking. The ruler is drawn on a &lt;canvas&gt; element, which even though it seems simple is actually a hardware-accelerated (potentially) rendering surface, right? So, there's probably some kind of constraint on just how huge those can be, right?

\*google\*, \*google\* (OK, in reality it took me literally 5 seconds of googling, I typed in "webkit canvas maximum size" and looked at the very first hit. Didn't even need to click on it.)

> For Google Chrome, the maximum allowable width and height are 32,767 pixels

"`timeline_webview:INFO Computed timeline width in pixels: 46294 (based on duration: 4629.4)`"

### **`Computed timeline width in pixels: 46294`**

## **"maximum allowable width and height are 32,767 pixels"**

![will](https://user-images.githubusercontent.com/538020/66443488-4c794080-ea0d-11e9-8a0a-1e1fb004263e.gif)

**Comment by ferdnyc** [comment]
(I also attempted to confirm my theory by turning on audio waveform display on my 76-minute timeline clip, since other than the ruler and the cache progress readout, clip waveforms are the only other &lt;canvas&gt; element on the timeline.

...That was 14 minutes ago, and my mouse pointer is still a wait-spinner.  I don't think it's coming back.)

But I'm sure I'm right, because remember @N3WWN's computations regarding the ruler constraints. Turns out, it's not multiples of 327 seconds that are the issue, but multiples of 327 * 100 pixels/tick.

The fix for this will be to construct the ruler as a _series_ of canvas elements, laid end-to-end-to-end in the ruler container, rather than creating one _giant_ canvas element. There's no reason at all that it needs to be one huge canvas.

...Rendering my video's `46,000px`-wide audio waveform, well, that's a bit trickier.

**Comment by mikelacsa** [comment]
This issue was fixed as mentioned in #3033

**Comment by N3WWN** [comment]
Thanks for re-opening this issue.  I just verified that it is still a problem with a recent v2.4.4-dev2 daily build. :)

**Comment by ferdnyc** [comment]
> Thanks for re-opening this issue. I just verified that it is still a problem with a recent v2.4.4-dev2 daily build. :)

Well, yeah, I know I certainly haven't fixed it. You saw my explanation above for _why_ it's happening, though, right? At least now we know that much, I guess. Doesn't exactly _fix_ anything, of course...

**Comment by Lurgainn** [comment]
Any news about this problem?
I'm trying to make a video that is about an hour long, and the fact that I'm not able to zoom too much because otherwise the ruler disappear, it create to me a lot of problems.
Anyway thanks so much for your work.

**Comment by injiniero** [comment]
I can confirm this bug with Ubuntu 18.04 64b and latest ppa release 2.5.1

**Comment by Lurgainn** [comment]
I don't want to put any pressure on the developer who I thank very much for his excellent work, but I'm curious to know if there is any prediction if this correction will be made and if so, in what timeframe.
Thanks

**Comment by Eate** [comment]
Reproduced with Ubuntu 20.04 amd64, version 2.5.1 (via stable PPA).

**Comment by nanohtpc** [comment]
same here

**Comment by Lurgainn** [comment]
I think that this still is a relevant bug that needs to be fixed.
Thanks

**Comment by N3WWN** [comment]
I was hoping this was resolved with the updates to the timeline/zoom code that we've seen in the recent dailies, but it is still an issue with the newest daily (OpenShot-v2.5.1-dev3-daily-7635-d9ea98eb-92ff6084-x86_64.dmg):

<img width="1149" alt="image" src="https://user-images.githubusercontent.com/19431804/123641312-22267280-d7f0-11eb-96df-f9bda0d8bcb1.png">

I can no longer tell what zoom level is currently displayed, but you can see that somewhere around 20m33s, the timeline stops displaying.

The latest updates also mean I can now get the playhead to detach from itself:

<img width="1157" alt="image" src="https://user-images.githubusercontent.com/19431804/123641635-75002a00-d7f0-11eb-9449-963556e0889e.png">

So that fun ;)

**Comment by JacksonRG** [comment]
@N3WWN Thanks for your examples. I've got a PR in review about this.

I think I need to account for some more changes in the zoom slider.

**Comment by Dipanshu-Kubde** [comment]
I am new here 
please, anyone, tell me how can I start here

**Comment by JacksonRG** [comment]
@Dipanshu-Kubde  Are you having issues with the ruler not fully drawing? I believe that has been fixed. We have made significant changes to how the ruler is drawn in the most recent stable release.

**Comment by rem747** [comment]
Hello,
I don't know if I should create a new thread for this bug.  It is related to the timeline lost of zoom in capability.
The bug I would like to report is for whatever reason (mistake or change in the project) we have to enter a lenghty element, then play with the zoom out button and then shorten the element again, then we lost the timeline zoom in capability.  In this video example at the end I am stuck with a timeline with minute precision.

https://user-images.githubusercontent.com/77164855/141560890-1d428a2f-f9cb-407c-b18f-e95d0d9ebdcb.mp4

.
![version](https://user-images.githubusercontent.com/77164855/141561062-7959f32f-0bc4-4109-a400-436e7d54c9d3.JPG)
.

**Comment by JacksonRG** [comment]
@rem747 For that particular issue, I'd recommend you use the +/- keys to zoom in and out.

I can also start working on making sure the zoom slider adjusts to the maximum length of the project

**Comment by JacksonRG** [comment]
@rem747 `Ctrl+ scrollwheel` should also allow you to scroll beyond limits for mouse controlls

**Comment by rem747** [comment]
> @rem747 For that particular issue, I'd recommend you use the +/- keys to zoom in and out.
> 
> I can also start working on making sure the zoom slider adjusts to the maximum length of the project

I have noticed that many tutorial have this +/- button, as u can see I don't have them.

Is it version related?

**Comment by rem747** [comment]
> @rem747 `Ctrl+ scrollwheel` should also allow you to scroll beyond limits for mouse controlls

Thanks u for this tip....u saved my project...I will not have to do it from the scratch...

**Comment by JacksonRG** [comment]
@rem747 Oh, I meant the plus and minus keys on your keyboard when I said `+/-`. Sorry about that

(Technically they're the - and = buttons. But I thought of them as plus and minus when I was editing the zoom code) :sweat_smile:

**Comment by N3WWN** [comment]
It looks like a fairly recent daily build no longer exhibits this issue.  Perhaps the PR from @JacksonRG resolved it?  
Can anyone else confirm that they cannot replicate the issue with the timeline rule cutoff?
